all: program
program :healthcenter1 patient1 doctor1

healthcenter1 : 
	g++ -o healthcenter healthcenter1.cpp 

patient1 : patient1.cpp
	g++ -o patient patient1.cpp 

doctor1 : doctor1.cpp
	g++ -o doctor doctor1.cpp 

clean:
	rm *.o
